Using node resolver to locate script dependencies
jamonholmgren/react-native-colo-loco pull request #30
Opened 2023-11-10 15:39 UTC by morganick

2023-11-11 00:17 UTC, jamonholmgren approved these changes

2023-11-11 00:20 UTC, jamonholmgren requested changes
We need to update `scripts/install-colo-loco` too, so it makes these changes.

I'll do that and push up an update to this branch.

2023-11-11 00:32 UTC, jamonholmgren commented
Update here, please review! https://github.com/jamonholmgren/react-native-colo-loco/pull/30/commits/2443531a29f7ef498c331ce73bff6e5135f413ed

2023-11-11 01:08 UTC, jamonholmgren commented
@morganick I'm not sure why my newest commit didn't make it into this PR. https://github.com/morganick/react-native-colo-loco/commit/81c38b239ede18ee3f872d82d8535b05ebc1a9b9

2023-11-11 20:06 UTC, jamonholmgren commented
Now they're there!

2023-11-14 13:47 UTC, morganick reviewed
There's a typo in the pathing for the iOS scripts. Will push a commit up shortly to fix.

2023-11-14 14:04 UTC, morganick commented on README.md
> +require File.join(File.dirname(`node --print "require.resolve('react-native-colo-loco/package.json')"`), "scripts/ios.rb")
🤦 forgot this was using `dirname` from ruby... ignore. More ☕ required.

2023-11-14 14:04 UTC, morganick commented on test/install-colo-loco.test.js
> +    expect(podfile).toContain("scripts/ios.rb")
ignore...

2023-11-14 14:11 UTC, morganick commented on test/install-colo-loco.test.js
> +    expect(settingsGradle).toContain("scripts/android.groovy")
I think it be more consistent to leave as is. The `../` is an implementation detail.

2023-11-14 14:11 UTC, morganick commented on scripts/install-colo-loco
> +require File.join(File.dirname(\`node --print "require.resolve('react-native-colo-loco/package.json')"\`), "scripts/ios.rb")
Ignore... I was thinking of the android side. We're using `dirname` here so we're g2g.

2023-11-14 14:13 UTC, morganick commented
Tests pass and I've reviewed the rest of the changes 👍

2023-11-15 17:01 UTC, jamonholmgren commented on test/install-colo-loco.test.js
> +    expect(settingsGradle).toContain("scripts/android.groovy")
Good call.

2023-11-15 17:01 UTC, jamonholmgren approved these changes

2023-11-15 17:02 UTC, merged